/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// ClusterNetworkPolicyProtocolsApplyConfiguration represents a declarative configuration of the ClusterNetworkPolicyProtocols type for use
// with apply.
type ClusterNetworkPolicyProtocolsApplyConfiguration struct {
	TCP                  []ClusterNetworkPolicyMatchTCPApplyConfiguration  `json:"tcp,omitempty"`
	UDP                  []ClusterNetworkPolicyMatchUDPApplyConfiguration  `json:"udp,omitempty"`
	DestinationNamedPort []ClusterNetworkPolicyNamedPortApplyConfiguration `json:"destinationNamedPort,omitempty"`
}

// ClusterNetworkPolicyProtocolsApplyConfiguration constructs a declarative configuration of the ClusterNetworkPolicyProtocols type for use with
// apply.
func ClusterNetworkPolicyProtocols() *ClusterNetworkPolicyProtocolsApplyConfiguration {
	return &ClusterNetworkPolicyProtocolsApplyConfiguration{}
}

// WithTCP adds the given value to the TCP field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TCP field.
func (b *ClusterNetworkPolicyProtocolsApplyConfiguration) WithTCP(values ...*ClusterNetworkPolicyMatchTCPApplyConfiguration) *ClusterNetworkPolicyProtocolsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTCP")
		}
		b.TCP = append(b.TCP, *values[i])
	}
	return b
}

// WithUDP adds the given value to the UDP field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the UDP field.
func (b *ClusterNetworkPolicyProtocolsApplyConfiguration) WithUDP(values ...*ClusterNetworkPolicyMatchUDPApplyConfiguration) *ClusterNetworkPolicyProtocolsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUDP")
		}
		b.UDP = append(b.UDP, *values[i])
	}
	return b
}

// WithDestinationNamedPort adds the given value to the DestinationNamedPort field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DestinationNamedPort field.
func (b *ClusterNetworkPolicyProtocolsApplyConfiguration) WithDestinationNamedPort(values ...*ClusterNetworkPolicyNamedPortApplyConfiguration) *ClusterNetworkPolicyProtocolsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDestinationNamedPort")
		}
		b.DestinationNamedPort = append(b.DestinationNamedPort, *values[i])
	}
	return b
}
