/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	apisv1alpha2 "sigs.k8s.io/network-policy-api/apis/v1alpha2"
)

// ClusterNetworkPolicyMatchApplyConfiguration represents a declarative configuration of the ClusterNetworkPolicyMatch type for use
// with apply.
type ClusterNetworkPolicyMatchApplyConfiguration struct {
	TCP       []apisv1alpha2.ClusterNetworkPolicyMatchTCP       `json:"tcp,omitempty"`
	UDP       []apisv1alpha2.ClusterNetworkPolicyMatchUDP       `json:"udp,omitempty"`
	ICMP      []ClusterNetworkPolicyMatchICMPApplyConfiguration `json:"icmp,omitempty"`
	NamedPort *string                                           `json:"namedPort,omitempty"`
}

// ClusterNetworkPolicyMatchApplyConfiguration constructs a declarative configuration of the ClusterNetworkPolicyMatch type for use with
// apply.
func ClusterNetworkPolicyMatch() *ClusterNetworkPolicyMatchApplyConfiguration {
	return &ClusterNetworkPolicyMatchApplyConfiguration{}
}

// WithTCP adds the given value to the TCP field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TCP field.
func (b *ClusterNetworkPolicyMatchApplyConfiguration) WithTCP(values ...apisv1alpha2.ClusterNetworkPolicyMatchTCP) *ClusterNetworkPolicyMatchApplyConfiguration {
	for i := range values {
		b.TCP = append(b.TCP, values[i])
	}
	return b
}

// WithUDP adds the given value to the UDP field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the UDP field.
func (b *ClusterNetworkPolicyMatchApplyConfiguration) WithUDP(values ...apisv1alpha2.ClusterNetworkPolicyMatchUDP) *ClusterNetworkPolicyMatchApplyConfiguration {
	for i := range values {
		b.UDP = append(b.UDP, values[i])
	}
	return b
}

// WithICMP adds the given value to the ICMP field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ICMP field.
func (b *ClusterNetworkPolicyMatchApplyConfiguration) WithICMP(values ...*ClusterNetworkPolicyMatchICMPApplyConfiguration) *ClusterNetworkPolicyMatchApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithICMP")
		}
		b.ICMP = append(b.ICMP, *values[i])
	}
	return b
}

// WithNamedPort sets the NamedPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamedPort field is set to the value of the last call.
func (b *ClusterNetworkPolicyMatchApplyConfiguration) WithNamedPort(value string) *ClusterNetworkPolicyMatchApplyConfiguration {
	b.NamedPort = &value
	return b
}
