/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// ClusterNetworkPolicyMatchPortApplyConfiguration represents a declarative configuration of the ClusterNetworkPolicyMatchPort type for use
// with apply.
type ClusterNetworkPolicyMatchPortApplyConfiguration struct {
	Number *int32                                                `json:"number,omitempty"`
	Range  *ClusterNetworkPolicyMatchPortRangeApplyConfiguration `json:"portRange,omitempty"`
}

// ClusterNetworkPolicyMatchPortApplyConfiguration constructs a declarative configuration of the ClusterNetworkPolicyMatchPort type for use with
// apply.
func ClusterNetworkPolicyMatchPort() *ClusterNetworkPolicyMatchPortApplyConfiguration {
	return &ClusterNetworkPolicyMatchPortApplyConfiguration{}
}

// WithNumber sets the Number field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Number field is set to the value of the last call.
func (b *ClusterNetworkPolicyMatchPortApplyConfiguration) WithNumber(value int32) *ClusterNetworkPolicyMatchPortApplyConfiguration {
	b.Number = &value
	return b
}

// WithRange sets the Range field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Range field is set to the value of the last call.
func (b *ClusterNetworkPolicyMatchPortApplyConfiguration) WithRange(value *ClusterNetworkPolicyMatchPortRangeApplyConfiguration) *ClusterNetworkPolicyMatchPortApplyConfiguration {
	b.Range = value
	return b
}
