/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apisv1alpha1 "sigs.k8s.io/network-policy-api/apis/v1alpha1"
)

// AdminNetworkPolicyLister helps list AdminNetworkPolicies.
// All objects returned here must be treated as read-only.
type AdminNetworkPolicyLister interface {
	// List lists all AdminNetworkPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1alpha1.AdminNetworkPolicy, err error)
	// Get retrieves the AdminNetworkPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apisv1alpha1.AdminNetworkPolicy, error)
	AdminNetworkPolicyListerExpansion
}

// adminNetworkPolicyLister implements the AdminNetworkPolicyLister interface.
type adminNetworkPolicyLister struct {
	listers.ResourceIndexer[*apisv1alpha1.AdminNetworkPolicy]
}

// NewAdminNetworkPolicyLister returns a new AdminNetworkPolicyLister.
func NewAdminNetworkPolicyLister(indexer cache.Indexer) AdminNetworkPolicyLister {
	return &adminNetworkPolicyLister{listers.New[*apisv1alpha1.AdminNetworkPolicy](indexer, apisv1alpha1.Resource("adminnetworkpolicy"))}
}
