authors:
  astoycos:
    name: Andrew Stoycos
    description: Senior Software Engineer at Red Hat. network-policy-api co-lead.
    avatar: https://github.com/astoycos.png
  Dyanngg:
    name: Yang Ding
    description: Senior Member of Technical Staff at VMware. network-policy-api co-lead.
    avatar: https://github.com/dyanngg.png  
  frozenprocess:
    name: Reza Ramezanpour
    description: Senior Developer Advocate at Tigera.
    avatar: https://github.com/frozenprocess.png