package connectivity

import (
	"testing"

	"github.com/stretchr/testify/require"
	"sigs.k8s.io/network-policy-api/policy-assistant/examples"
	"sigs.k8s.io/network-policy-api/policy-assistant/pkg/kube/netpol"
	"sigs.k8s.io/network-policy-api/policy-assistant/pkg/matcher"
)

func TestExplain(t *testing.T) {
	t.Run("prints network policies v1", func(t *testing.T) {
		expected := "+---------+--------------------+----------------------------------------------------------------------------+----------------------+--------------------+---------------------------+\n" +
			"|  TYPE   |      SUBJECT       |                                SOURCE RULES                                |         PEER         |       ACTION       |       PORT/PROTOCOL       |\n" +
			"+---------+--------------------+----------------------------------------------------------------------------+----------------------+--------------------+---------------------------+\n" +
			"| Ingress | Namespace:         | [NPv1] default/accidental-and                                              | Namespace:           | NPv1:              | all ports, all protocols  |\n" +
			"|         |    default         | [NPv1] default/accidental-or                                               |    default           |    Allow any peers |                           |\n" +
			"|         | Pod:               |                                                                            | Pod:                 |                    |                           |\n" +
			"|         |    a = b           |                                                                            |    role = client     |                    |                           |\n" +
			"+         +                    +                                                                            +----------------------+                    +                           +\n" +
			"|         |                    |                                                                            | Namespace:           |                    |                           |\n" +
			"|         |                    |                                                                            |    user = alice      |                    |                           |\n" +
			"|         |                    |                                                                            | Pod:                 |                    |                           |\n" +
			"|         |                    |                                                                            |    role = client     |                    |                           |\n" +
			"+         +                    +                                                                            +----------------------+                    +                           +\n" +
			"|         |                    |                                                                            | Namespace:           |                    |                           |\n" +
			"|         |                    |                                                                            |    user = alice      |                    |                           |\n" +
			"|         |                    |                                                                            | Pod:                 |                    |                           |\n" +
			"|         |                    |                                                                            |    all               |                    |                           |\n" +
			"+         +--------------------+----------------------------------------------------------------------------+----------------------+                    +---------------------------+\n" +
			"|         | Namespace:         | [NPv1] default/allow-nothing-to-v2-all-web                                 | no peers             |                    | none                      |\n" +
			"|         |    default         |                                                                            |                      |                    |                           |\n" +
			"|         | Pod:               |                                                                            |                      |                    |                           |\n" +
			"|         |    all = web       |                                                                            |                      |                    |                           |\n" +
			"+         +--------------------+----------------------------------------------------------------------------+----------------------+                    +---------------------------+\n" +
			"|         | Namespace:         | [NPv1] default/allow-specific-port-from-role-monitoring-to-app-apiserver   | Namespace:           |                    | port 5000 on protocol TCP |\n" +
			"|         |    default         |                                                                            |    default           |                    |                           |\n" +
			"|         | Pod:               |                                                                            | Pod:                 |                    |                           |\n" +
			"|         |    app = apiserver |                                                                            |    role = monitoring |                    |                           |\n" +
			"+         +--------------------+----------------------------------------------------------------------------+----------------------+                    +---------------------------+\n" +
			"|         | Namespace:         | [NPv1] default/allow-from-app-bookstore-to-app-bookstore-role-api          | Namespace:           |                    | all ports, all protocols  |\n" +
			"|         |    default         |                                                                            |    default           |                    |                           |\n" +
			"|         | Pod:               |                                                                            | Pod:                 |                    |                           |\n" +
			"|         |    app = bookstore |                                                                            |    app = bookstore   |                    |                           |\n" +
			"|         |    role = api      |                                                                            |                      |                    |                           |\n" +
			"+         +--------------------+----------------------------------------------------------------------------+----------------------+                    +                           +\n" +
			"|         | Namespace:         | [NPv1] default/allow-from-multiple-to-app-bookstore-role-db                | Namespace:           |                    |                           |\n" +
			"|         |    default         |                                                                            |    default           |                    |                           |\n" +
			"|         | Pod:               |                                                                            | Pod:                 |                    |                           |\n" +
			"|         |    app = bookstore |                                                                            |    app = bookstore   |                    |                           |\n" +
			"|         |    role = db       |                                                                            |    role = api        |                    |                           |\n" +
			"+         +                    +                                                                            +----------------------+                    +                           +\n" +
			"|         |                    |                                                                            | Namespace:           |                    |                           |\n" +
			"|         |                    |                                                                            |    default           |                    |                           |\n" +
			"|         |                    |                                                                            | Pod:                 |                    |                           |\n" +
			"|         |                    |                                                                            |    app = bookstore   |                    |                           |\n" +
			"|         |                    |                                                                            |    role = search     |                    |                           |\n" +
			"+         +                    +                                                                            +----------------------+                    +                           +\n" +
			"|         |                    |                                                                            | Namespace:           |                    |                           |\n" +
			"|         |                    |                                                                            |    default           |                    |                           |\n" +
			"|         |                    |                                                                            | Pod:                 |                    |                           |\n" +
			"|         |                    |                                                                            |    app = inventory   |                    |                           |\n" +
			"|         |                    |                                                                            |    role = web        |                    |                           |\n" +
			"+         +--------------------+----------------------------------------------------------------------------+----------------------+                    +---------------------------+\n" +
			"|         | Namespace:         | [NPv1] default/allow-nothing                                               | no peers             |                    | none                      |\n" +
			"|         |    default         |                                                                            |                      |                    |                           |\n" +
			"|         | Pod:               |                                                                            |                      |                    |                           |\n" +
			"|         |    app = foo       |                                                                            |                      |                    |                           |\n" +
			"+         +--------------------+----------------------------------------------------------------------------+----------------------+                    +---------------------------+\n" +
			"|         | Namespace:         | [NPv1] default/allow-all-to-app-web                                        | all pods, all ips    |                    | all ports, all protocols  |\n" +
			"|         |    default         | [NPv1] default/allow-all-to-version2-app-web                               |                      |                    |                           |\n" +
			"|         | Pod:               | [NPv1] default/allow-all-to-version3-app-web                               |                      |                    |                           |\n" +
			"|         |    app = web       | [NPv1] default/allow-all-to-version4-app-web                               |                      |                    |                           |\n" +
			"|         |                    | [NPv1] default/allow-from-anywhere-to-app-web                              |                      |                    |                           |\n" +
			"|         |                    | [NPv1] default/allow-from-namespace-to-app-web                             |                      |                    |                           |\n" +
			"|         |                    | [NPv1] default/allow-from-namespace-with-labels-type-monitoring-to-app-web |                      |                    |                           |\n" +
			"|         |                    | [NPv1] default/allow-nothing-to-app-web                                    |                      |                    |                           |\n" +
			"+         +--------------------+----------------------------------------------------------------------------+----------------------+                    +                           +\n" +
			"|         | Namespace:         | [NPv1] default/allow-all-within-namespace                                  | Namespace:           |                    |                           |\n" +
			"|         |    default         | [NPv1] default/allow-nothing-to-anything                                   |    default           |                    |                           |\n" +
			"|         | Pod:               |                                                                            | Pod:                 |                    |                           |\n" +
			"|         |    all pods        |                                                                            |    all               |                    |                           |\n" +
			"+---------+--------------------+----------------------------------------------------------------------------+----------------------+--------------------+---------------------------+\n" +
			"|         |                    |                                                                            |                      |                    |                           |\n" +
			"+---------+--------------------+----------------------------------------------------------------------------+----------------------+--------------------+---------------------------+\n" +
			"| Egress  | Namespace:         | [NPv1] default/allow-egress-on-port-app-foo                                | all pods, all ips    | NPv1:              | port 53 on protocol TCP   |\n" +
			"|         |    default         | [NPv1] default/allow-egress-to-all-namespace-from-app-foo-on-port-53       |                      |    Allow any peers | port 53 on protocol UDP   |\n" +
			"|         | Pod:               | [NPv1] default/allow-no-egress-from-labels-app-foo                         |                      |                    |                           |\n" +
			"|         |    app = foo       | [NPv1] default/allow-nothing                                               |                      |                    |                           |\n" +
			"+         +--------------------+----------------------------------------------------------------------------+----------------------+                    +---------------------------+\n" +
			"|         | Namespace:         | [NPv1] default/allow-no-egress-from-namespace                              | no peers             |                    | none                      |\n" +
			"|         |    default         |                                                                            |                      |                    |                           |\n" +
			"|         | Pod:               |                                                                            |                      |                    |                           |\n" +
			"|         |    all pods        |                                                                            |                      |                    |                           |\n" +
			"+---------+--------------------+----------------------------------------------------------------------------+----------------------+--------------------+---------------------------+\n" +
			""
		policies := matcher.BuildV1AndV2NetPols(true, netpol.AllExamples, nil, nil)
		require.Equal(t, expected, policies.ExplainTable())
	})

	t.Run("prints network ANPs and BANPs", func(t *testing.T) {
		expected := "+---------+------------------------------------------+-----------------------------+------------------------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------+\n" +
			"|  TYPE   |                 SUBJECT                  |        SOURCE RULES         |                                  PEER                                  |                                        ACTION                                        |       PORT/PROTOCOL        |\n" +
			"+---------+------------------------------------------+-----------------------------+------------------------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------+\n" +
			"| Ingress | Namespace:                               | [ANP] default/example-anp   | Namespace:                                                             | ANP:                                                                                 | all ports, all protocols   |\n" +
			"|         |    kubernetes.io/metadata.name Exists [] | [ANP] default/example-anp-2 |    kubernetes.io/metadata.name = network-policy-conformance-hufflepuff |    pri=16 (deny-from-hufflepuff-everything-else-2): Deny                             |                            |\n" +
			"|         |                                          | [BANP] default/default      | Pod:                                                                   |    pri=20 (deny-from-hufflepuff-everything-else): Deny                               |                            |\n" +
			"|         |                                          |                             |    all                                                                 | BANP:                                                                                |                            |\n" +
			"|         |                                          |                             |                                                                        |    Deny                                                                              |                            |\n" +
			"+         +                                          +                             +------------------------------------------------------------------------+--------------------------------------------------------------------------------------+                            +\n" +
			"|         |                                          |                             | Namespace:                                                             | ANP:                                                                                 |                            |\n" +
			"|         |                                          |                             |    kubernetes.io/metadata.name = network-policy-conformance-ravenclaw  |    pri=16 (allow-from-ravenclaw-everything-2): Allow (ineffective rules: Deny, Pass) |                            |\n" +
			"|         |                                          |                             | Pod:                                                                   |    pri=20 (allow-from-ravenclaw-everything): Allow (ineffective rules: Deny, Pass)   |                            |\n" +
			"|         |                                          |                             |    all                                                                 | BANP:                                                                                |                            |\n" +
			"|         |                                          |                             |                                                                        |    Allow                                                                             |                            |\n" +
			"+         +                                          +                             +------------------------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------+\n" +
			"|         |                                          |                             | Namespace:                                                             | ANP:                                                                                 | port 80 on protocol TCP    |\n" +
			"|         |                                          |                             |    kubernetes.io/metadata.name = network-policy-conformance-slytherin  |    pri=16 (deny-from-slytherin-at-port-80-53-9003-2): Deny (ineffective rules: Pass) | port 53 on protocol UDP    |\n" +
			"|         |                                          |                             | Pod:                                                                   |    pri=20 (deny-from-slytherin-at-port-80-53-9003): Deny (ineffective rules: Pass)   | port 9003 on protocol SCTP |\n" +
			"|         |                                          |                             |    all                                                                 | BANP:                                                                                |                            |\n" +
			"|         |                                          |                             |                                                                        |    Deny                                                                              |                            |\n" +
			"+         +                                          +                             +------------------------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------+\n" +
			"|         |                                          |                             | Namespace:                                                             | ANP:                                                                                 | port 80 on protocol TCP    |\n" +
			"|         |                                          |                             |    kubernetes.io/metadata.name = network-policy-conformance-hufflepuff |    pri=16 (allow-from-hufflepuff-at-port-80-5353-9003-2): Allow                      | port 5353 on protocol UDP  |\n" +
			"|         |                                          |                             | Pod:                                                                   |    pri=20 (allow-from-hufflepuff-at-port-80-5353-9003): Allow                        | port 9003 on protocol SCTP |\n" +
			"|         |                                          |                             |    all                                                                 | BANP:                                                                                |                            |\n" +
			"|         |                                          |                             |                                                                        |    Allow                                                                             |                            |\n" +
			"+---------+------------------------------------------+-----------------------------+------------------------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------+\n" +
			"|         |                                          |                             |                                                                        |                                                                                      |                            |\n" +
			"+---------+------------------------------------------+-----------------------------+------------------------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------+\n" +
			"| Egress  | Namespace:                               | [ANP] default/example-anp   | Namespace:                                                             | BANP:                                                                                | all ports, all protocols   |\n" +
			"|         |    kubernetes.io/metadata.name Exists [] | [ANP] default/example-anp-2 |    Not Same labels - Test1                                             |    Deny                                                                              |                            |\n" +
			"|         |                                          | [BANP] default/default      | Pod:                                                                   |                                                                                      |                            |\n" +
			"|         |                                          |                             |    all                                                                 |                                                                                      |                            |\n" +
			"+         +                                          +                             +------------------------------------------------------------------------+--------------------------------------------------------------------------------------+                            +\n" +
			"|         |                                          |                             | Namespace:                                                             | BANP:                                                                                |                            |\n" +
			"|         |                                          |                             |    Same labels - Test                                                  |    Allow                                                                             |                            |\n" +
			"|         |                                          |                             | Pod:                                                                   |                                                                                      |                            |\n" +
			"|         |                                          |                             |    all                                                                 |                                                                                      |                            |\n" +
			"+         +                                          +                             +------------------------------------------------------------------------+--------------------------------------------------------------------------------------+                            +\n" +
			"|         |                                          |                             | Namespace:                                                             | ANP:                                                                                 |                            |\n" +
			"|         |                                          |                             |    kubernetes.io/metadata.name = network-policy-conformance-hufflepuff |    pri=16 (deny-to-hufflepuff-everything-else-2): Deny                               |                            |\n" +
			"|         |                                          |                             | Pod:                                                                   |    pri=20 (deny-to-hufflepuff-everything-else): Deny                                 |                            |\n" +
			"|         |                                          |                             |    all                                                                 | BANP:                                                                                |                            |\n" +
			"|         |                                          |                             |                                                                        |    Deny                                                                              |                            |\n" +
			"+         +                                          +                             +------------------------------------------------------------------------+--------------------------------------------------------------------------------------+                            +\n" +
			"|         |                                          |                             | Namespace:                                                             | ANP:                                                                                 |                            |\n" +
			"|         |                                          |                             |    kubernetes.io/metadata.name = network-policy-conformance-ravenclaw  |    pri=16 (allow-to-ravenclaw-everything-2): Allow (ineffective rules: Deny, Pass)   |                            |\n" +
			"|         |                                          |                             | Pod:                                                                   |    pri=20 (allow-to-ravenclaw-everything): Allow (ineffective rules: Deny, Pass)     |                            |\n" +
			"|         |                                          |                             |    all                                                                 |                                                                                      |                            |\n" +
			"+         +                                          +                             +------------------------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------+\n" +
			"|         |                                          |                             | Namespace:                                                             | ANP:                                                                                 | port 80 on protocol TCP    |\n" +
			"|         |                                          |                             |    kubernetes.io/metadata.name = network-policy-conformance-slytherin  |    pri=16 (deny-to-slytherin-at-ports-80-53-9003-2): Deny (ineffective rules: Pass)  | port 53 on protocol UDP    |\n" +
			"|         |                                          |                             | Pod:                                                                   |    pri=20 (deny-to-slytherin-at-ports-80-53-9003): Deny (ineffective rules: Pass)    | port 9003 on protocol SCTP |\n" +
			"|         |                                          |                             |    all                                                                 |                                                                                      |                            |\n" +
			"+         +                                          +                             +------------------------------------------------------------------------+--------------------------------------------------------------------------------------+                            +\n" +
			"|         |                                          |                             | Namespace:                                                             | BANP:                                                                                |                            |\n" +
			"|         |                                          |                             |    kubernetes.io/metadata.name Exists []                               |    Deny                                                                              |                            |\n" +
			"|         |                                          |                             | Pod:                                                                   |                                                                                      |                            |\n" +
			"|         |                                          |                             |    all                                                                 |                                                                                      |                            |\n" +
			"+         +                                          +                             +------------------------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------+\n" +
			"|         |                                          |                             | Namespace:                                                             | ANP:                                                                                 | port 8080 on protocol TCP  |\n" +
			"|         |                                          |                             |    kubernetes.io/metadata.name = network-policy-conformance-hufflepuff |    pri=16 (allow-to-hufflepuff-at-ports-8080-5353-2): Allow                          | port 5353 on protocol UDP  |\n" +
			"|         |                                          |                             | Pod:                                                                   |    pri=20 (allow-to-hufflepuff-at-ports-8080-5353): Allow                            | port 9003 on protocol SCTP |\n" +
			"|         |                                          |                             |    all                                                                 | BANP:                                                                                |                            |\n" +
			"|         |                                          |                             |                                                                        |    Allow                                                                             |                            |\n" +
			"+---------+------------------------------------------+-----------------------------+------------------------------------------------------------------------+--------------------------------------------------------------------------------------+----------------------------+\n" +
			""
		policies := matcher.BuildV1AndV2NetPols(false, nil, examples.CoreGressRulesCombinedANB, examples.CoreGressRulesCombinedBANB)
		require.Equal(t, expected, policies.ExplainTable())
	})
}
