/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apisv1beta1 "sigs.k8s.io/network-policy-api/apis/v1beta1"
	applyconfigurationapisv1beta1 "sigs.k8s.io/network-policy-api/pkg/client/applyconfiguration/apis/v1beta1"
	scheme "sigs.k8s.io/network-policy-api/pkg/client/clientset/versioned/scheme"
)

// ClusterNetworkPoliciesGetter has a method to return a ClusterNetworkPolicyInterface.
// A group's client should implement this interface.
type ClusterNetworkPoliciesGetter interface {
	ClusterNetworkPolicies() ClusterNetworkPolicyInterface
}

// ClusterNetworkPolicyInterface has methods to work with ClusterNetworkPolicy resources.
type ClusterNetworkPolicyInterface interface {
	Create(ctx context.Context, clusterNetworkPolicy *apisv1beta1.ClusterNetworkPolicy, opts v1.CreateOptions) (*apisv1beta1.ClusterNetworkPolicy, error)
	Update(ctx context.Context, clusterNetworkPolicy *apisv1beta1.ClusterNetworkPolicy, opts v1.UpdateOptions) (*apisv1beta1.ClusterNetworkPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterNetworkPolicy *apisv1beta1.ClusterNetworkPolicy, opts v1.UpdateOptions) (*apisv1beta1.ClusterNetworkPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apisv1beta1.ClusterNetworkPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apisv1beta1.ClusterNetworkPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apisv1beta1.ClusterNetworkPolicy, err error)
	Apply(ctx context.Context, clusterNetworkPolicy *applyconfigurationapisv1beta1.ClusterNetworkPolicyApplyConfiguration, opts v1.ApplyOptions) (result *apisv1beta1.ClusterNetworkPolicy, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterNetworkPolicy *applyconfigurationapisv1beta1.ClusterNetworkPolicyApplyConfiguration, opts v1.ApplyOptions) (result *apisv1beta1.ClusterNetworkPolicy, err error)
	ClusterNetworkPolicyExpansion
}

// clusterNetworkPolicies implements ClusterNetworkPolicyInterface
type clusterNetworkPolicies struct {
	*gentype.ClientWithListAndApply[*apisv1beta1.ClusterNetworkPolicy, *apisv1beta1.ClusterNetworkPolicyList, *applyconfigurationapisv1beta1.ClusterNetworkPolicyApplyConfiguration]
}

// newClusterNetworkPolicies returns a ClusterNetworkPolicies
func newClusterNetworkPolicies(c *PolicyV1beta1Client) *clusterNetworkPolicies {
	return &clusterNetworkPolicies{
		gentype.NewClientWithListAndApply[*apisv1beta1.ClusterNetworkPolicy, *apisv1beta1.ClusterNetworkPolicyList, *applyconfigurationapisv1beta1.ClusterNetworkPolicyApplyConfiguration](
			"clusternetworkpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apisv1beta1.ClusterNetworkPolicy { return &apisv1beta1.ClusterNetworkPolicy{} },
			func() *apisv1beta1.ClusterNetworkPolicyList { return &apisv1beta1.ClusterNetworkPolicyList{} },
		),
	}
}
