/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/network-policy-api/apis/v1alpha1"
	apisv1alpha1 "sigs.k8s.io/network-policy-api/pkg/client/applyconfiguration/apis/v1alpha1"
)

// FakeBaselineAdminNetworkPolicies implements BaselineAdminNetworkPolicyInterface
type FakeBaselineAdminNetworkPolicies struct {
	Fake *FakePolicyV1alpha1
}

var baselineadminnetworkpoliciesResource = v1alpha1.SchemeGroupVersion.WithResource("baselineadminnetworkpolicies")

var baselineadminnetworkpoliciesKind = v1alpha1.SchemeGroupVersion.WithKind("BaselineAdminNetworkPolicy")

// Get takes name of the baselineAdminNetworkPolicy, and returns the corresponding baselineAdminNetworkPolicy object, and an error if there is any.
func (c *FakeBaselineAdminNetworkPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BaselineAdminNetworkPolicy, err error) {
	emptyResult := &v1alpha1.BaselineAdminNetworkPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(baselineadminnetworkpoliciesResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.BaselineAdminNetworkPolicy), err
}

// List takes label and field selectors, and returns the list of BaselineAdminNetworkPolicies that match those selectors.
func (c *FakeBaselineAdminNetworkPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BaselineAdminNetworkPolicyList, err error) {
	emptyResult := &v1alpha1.BaselineAdminNetworkPolicyList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(baselineadminnetworkpoliciesResource, baselineadminnetworkpoliciesKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BaselineAdminNetworkPolicyList{ListMeta: obj.(*v1alpha1.BaselineAdminNetworkPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.BaselineAdminNetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested baselineAdminNetworkPolicies.
func (c *FakeBaselineAdminNetworkPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(baselineadminnetworkpoliciesResource, opts))
}

// Create takes the representation of a baselineAdminNetworkPolicy and creates it.  Returns the server's representation of the baselineAdminNetworkPolicy, and an error, if there is any.
func (c *FakeBaselineAdminNetworkPolicies) Create(ctx context.Context, baselineAdminNetworkPolicy *v1alpha1.BaselineAdminNetworkPolicy, opts v1.CreateOptions) (result *v1alpha1.BaselineAdminNetworkPolicy, err error) {
	emptyResult := &v1alpha1.BaselineAdminNetworkPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(baselineadminnetworkpoliciesResource, baselineAdminNetworkPolicy, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.BaselineAdminNetworkPolicy), err
}

// Update takes the representation of a baselineAdminNetworkPolicy and updates it. Returns the server's representation of the baselineAdminNetworkPolicy, and an error, if there is any.
func (c *FakeBaselineAdminNetworkPolicies) Update(ctx context.Context, baselineAdminNetworkPolicy *v1alpha1.BaselineAdminNetworkPolicy, opts v1.UpdateOptions) (result *v1alpha1.BaselineAdminNetworkPolicy, err error) {
	emptyResult := &v1alpha1.BaselineAdminNetworkPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(baselineadminnetworkpoliciesResource, baselineAdminNetworkPolicy, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.BaselineAdminNetworkPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBaselineAdminNetworkPolicies) UpdateStatus(ctx context.Context, baselineAdminNetworkPolicy *v1alpha1.BaselineAdminNetworkPolicy, opts v1.UpdateOptions) (result *v1alpha1.BaselineAdminNetworkPolicy, err error) {
	emptyResult := &v1alpha1.BaselineAdminNetworkPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(baselineadminnetworkpoliciesResource, "status", baselineAdminNetworkPolicy, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.BaselineAdminNetworkPolicy), err
}

// Delete takes name of the baselineAdminNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeBaselineAdminNetworkPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(baselineadminnetworkpoliciesResource, name, opts), &v1alpha1.BaselineAdminNetworkPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBaselineAdminNetworkPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(baselineadminnetworkpoliciesResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BaselineAdminNetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched baselineAdminNetworkPolicy.
func (c *FakeBaselineAdminNetworkPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BaselineAdminNetworkPolicy, err error) {
	emptyResult := &v1alpha1.BaselineAdminNetworkPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(baselineadminnetworkpoliciesResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.BaselineAdminNetworkPolicy), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied baselineAdminNetworkPolicy.
func (c *FakeBaselineAdminNetworkPolicies) Apply(ctx context.Context, baselineAdminNetworkPolicy *apisv1alpha1.BaselineAdminNetworkPolicyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BaselineAdminNetworkPolicy, err error) {
	if baselineAdminNetworkPolicy == nil {
		return nil, fmt.Errorf("baselineAdminNetworkPolicy provided to Apply must not be nil")
	}
	data, err := json.Marshal(baselineAdminNetworkPolicy)
	if err != nil {
		return nil, err
	}
	name := baselineAdminNetworkPolicy.Name
	if name == nil {
		return nil, fmt.Errorf("baselineAdminNetworkPolicy.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.BaselineAdminNetworkPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(baselineadminnetworkpoliciesResource, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.BaselineAdminNetworkPolicy), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeBaselineAdminNetworkPolicies) ApplyStatus(ctx context.Context, baselineAdminNetworkPolicy *apisv1alpha1.BaselineAdminNetworkPolicyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BaselineAdminNetworkPolicy, err error) {
	if baselineAdminNetworkPolicy == nil {
		return nil, fmt.Errorf("baselineAdminNetworkPolicy provided to Apply must not be nil")
	}
	data, err := json.Marshal(baselineAdminNetworkPolicy)
	if err != nil {
		return nil, err
	}
	name := baselineAdminNetworkPolicy.Name
	if name == nil {
		return nil, fmt.Errorf("baselineAdminNetworkPolicy.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.BaselineAdminNetworkPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(baselineadminnetworkpoliciesResource, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.BaselineAdminNetworkPolicy), err
}
