name: Kind CNI From Job
on:
  workflow_dispatch:
    inputs:
      cni:
        description: "name of CNI to use"
        required: true

jobs:
  test-kind-calico:
    name: Run policy-assistant on KinD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5

      - name: Run policy-assistant
        working-directory: hack/kind
        run: CNI=${{ github.event.inputs.cni }} RUN_FROM_SOURCE=false ./run-policy-assistant.sh
